### ISSUE TITLE
Mini DisplayPort

### ISSUE THREAD

**Issue by CL-Jeremy** [osxfr33k/Asus-G750JX#1]
I've been using your work since 2015, but noticed only recently that miniDP isn't outputting properly, neither on 10.11 nor on 10.14 (which I am currently using). I didn't find the final conclusion on this in the ROG forum, so I'm raising this issue here as I believe it also applies to later versions.

I'm using a German version of G750JX with practically identical configuration as your DB71. The GTX 770M is driven by native drivers from the OS and is able to output HDMI signal just fine. miniDP works fine under Windows. Thunderbolt works on both Windows and macOS.

I'd very much appreciate your help. Many thanks in advance!

**Comment by osxfr33k** [comment]
I have not tested the Mini Display port only HDMI Port.

**Comment by CL-Jeremy** [comment]
Wow! Thanks for replying.

Of course I did resolve to using HDMI at last. Didn't have time to fiddle with DSDT too much. Currently still daily driving 10.14. Thanks again!

**Comment by osxfr33k** [comment]
I have done testing with Display port I went into Bios changed to Debug under Intel Thunderbolt then reboot and I was able to mount thunderbolt drives.  I went back into Bios and changed it back to normal.  I think you cannot hot swap thunderbolt drives you must boot while they are connected but it works well both in Clover and OPenCore v0.6.6.  I am going to share my OC EFI now but you will need to run GenSMBIOS look for it in Dortania OpenCOre Guide to create a new SMBIOS for MAcBookPro11,2

**Comment by CL-Jeremy** [comment]
Wait... I'm not talking about Thunderbolt. Drives and hubs work just fine and I'm not using a Thunderbolt-based monitor by any means. I'm just thinking of framebuffer kernel extension-related issues, as a real MacBook Pro would have a multiplexer for Intel HD Graphics, whereas both are not present on our machine. NVidia framebuffer kexts are less studied than AMD and Intel ones, I suppose, so I'm not that surprised after all.

**Comment by osxfr33k** [comment]
I did not read your initial post carefully enough and you do say Thunderbolt is working for you.  That port also servers as a miniDP and I have never been able to get any signal from it as a DP.  I do notice when I connect the miniDP to LCD or TV monitor I see the G750JX blank out for a second like it does for HDMI just before the 2nd monitor signal kicks in, I do see this with the miniDP but it never actually completes the signal.  I think I may not being using a good cable I will try a different one and let you know.  I have updated the github for OpenCore Catalina and BigSur both working great with those OpenCore EFI folders/files I have included.

**Comment by osxfr33k** [comment]
I tried with a better cable must be as you say a MacOS driver issue.  I am unsure if we can add more to the device properties for nvidia to enable this as a DP port in MacOS.  Since we have never been able to resolve since Mavericks I am going to close the topic for now and maybe someday re-open this for further investigation.
