### ISSUE TITLE
Big Sur Update?

### ISSUE THREAD

**Issue by DaveforScale** [osxfr33k/Asus-G750JX#3]
Hello, I have been following you since Mojave.
Since still being noob with hackintosh stuff, may I ask for your EFI file if you have updated to Big Sur.

Thanks,

**Comment by osxfr33k** [comment]
I am still waiting eventually I will try both Big Sur and OpenCore Bootloader in time.

Edited:  I have finished configuring OpenCore but only tested in Catalina not Big Sur.  You will need to get GenSMBIOS to generate a Serial and UUID before using the OPenCore Bootloader.  See the Dortania Guide it has a link to it and then read how to use it.

**Comment by osxfr33k** [comment]
I have Opencore for both Catalina and BigSur.  Make sure you use the correct one.
